apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: myapp  # Namespace for the deployment
  labels:
    app: nginx
spec:
  replicas: 2  # Number of replicas (pods) to create
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: myapp  # Namespace for the service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
