apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-app-versions
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: new-nginx
            namespace: myapp
            targetRevision: 0.1.0
          - name: nginx-chart
            namespace: myapp
            targetRevision: 0.2.0
            targetRevision: {{ Values.tergertREsion}}
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: default
      source:
        repoURL: https://artifacts.i.mercedes-benz.com/artifactory/sqms-helm-virtual
        chart: "{{name}}"
        targetRevision: "{{targetRevision}}"  # Version from the external file
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true