apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-app-versions
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: {{ .Values.repo.name }}
            namespace: myapp
            targetRevision: {{ .Values.repo.targetVersion }}
          - name: nginx-chart
            namespace: myapp
            targetRevision: 0.2.0
  template:
    metadata:
      name: "{{`{{ name }}`}}"
    spec:
      project: default
      source:
        repoURL: https://artifacts.i.mercedes-benz.com/artifactory/sqms-helm-virtual
        chart: "{{`{{ name }}`}}"
        targetRevision: "{{`{{ targetRevision }}`}}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{`{{ namespace }}`}}"
      syncPolicy:
        # automated:
        #   prune: true  # Removes resources that are no longer defined in the chart
        #   selfHeal: true  # Automatically sync if drift is detected
        syncOptions:
          - DryRun=true
